# Generated by Django 3.2.10 on 2021-12-11 18:28

from django.db import migrations, models
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a particular member', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('role', models.CharField(blank=True, choices=[('r', 'Regular'), ('a', 'Admin')], default='r', help_text='Role of the member', max_length=1)),
            ],
        ),
    ]
